"""initial schema

Revision ID: 0e3f01f9c238
Revises:
Create Date: 2026-07-11 17:30:18.972533
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0e3f01f9c238"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_usage_daily",
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("request_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("input_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "estimated_cost_usd",
            sa.Numeric(precision=12, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("usage_date", "model", name=op.f("pk_api_usage_daily")),
    )
    op.create_table(
        "application_settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_application_settings")),
    )
    op.create_table(
        "classification_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=False),
        sa.Column("stage", sa.SmallInteger(), nullable=False),
        sa.Column("result", sa.String(length=30), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("reason_code", sa.String(length=100), nullable=True),
        sa.Column("context_used", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("input_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("output_tokens", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "estimated_cost_usd",
            sa.Numeric(precision=12, scale=6),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint("stage IN (1, 2)", name=op.f("ck_classification_runs_stage_valid")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classification_runs")),
        sa.UniqueConstraint(
            "telegram_chat_id",
            "telegram_message_id",
            "stage",
            name="uq_classification_runs_message_stage",
        ),
    )
    op.create_table(
        "monitored_chats",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column(
            "chat_type",
            sa.Enum("group", "supergroup", "forum_supergroup", name="monitored_chat_type"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending_verification",
                "active",
                "access_lost",
                "read_only",
                "disabled",
                "verification_failed",
                name="monitored_chat_status",
            ),
            server_default="pending_verification",
            nullable=False,
        ),
        sa.Column("added_by_telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()"), nullable=False
        ),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_message_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("access_lost_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitored_chats")),
        sa.UniqueConstraint("telegram_chat_id", name=op.f("uq_monitored_chats_telegram_chat_id")),
    )
    op.create_index(
        "idx_monitored_chats_active",
        "monitored_chats",
        ["telegram_chat_id"],
        unique=False,
        postgresql_where=sa.text("status = 'active'"),
    )
    op.create_table(
        "translation_languages",
        sa.Column("language_code", sa.String(length=10), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_required", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.Column("installation_status", sa.String(length=20), nullable=False),
        sa.Column("installed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "installation_status IN ('not_installed', 'installing', 'installed', 'failed')",
            name=op.f("ck_translation_languages_installation_status_valid"),
        ),
        sa.CheckConstraint(
            "NOT is_required OR is_enabled", name=op.f("ck_translation_languages_required_enabled")
        ),
        sa.PrimaryKeyConstraint("language_code", name=op.f("pk_translation_languages")),
    )
    op.create_table(
        "detected_questions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monitored_chat_id", sa.UUID(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=True),
        sa.Column("topic_title", sa.String(length=255), nullable=True),
        sa.Column("author_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("author_display_name", sa.String(length=255), nullable=True),
        sa.Column("telegram_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=True),
        sa.Column("source_language", sa.String(length=10), nullable=True),
        sa.Column("category", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "detected",
                "waiting_for_draft",
                "waiting_confirmation",
                "send_requested",
                "sent",
                "send_failed",
                "dismissed",
                "cancelled",
                name="question_status",
            ),
            server_default="detected",
            nullable=False,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW() + INTERVAL '60 days'"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["monitored_chat_id"],
            ["monitored_chats.id"],
            name=op.f("fk_detected_questions_monitored_chat_id_monitored_chats"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detected_questions")),
        sa.UniqueConstraint(
            "telegram_chat_id", "telegram_message_id", name="uq_detected_questions_telegram_message"
        ),
    )
    op.create_index(
        "idx_detected_questions_expiry", "detected_questions", ["expires_at"], unique=False
    )
    op.create_index(
        "idx_detected_questions_operator_queue",
        "detected_questions",
        ["status", "detected_at"],
        unique=False,
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("monitored_chat_id", sa.UUID(), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=True),
        sa.Column("sender_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("sender_display_name", sa.String(length=255), nullable=True),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("telegram_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "processing", "retry", name="processing_job_status"),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW() + INTERVAL '24 hours'"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["monitored_chat_id"],
            ["monitored_chats.id"],
            name=op.f("fk_processing_jobs_monitored_chat_id_monitored_chats"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processing_jobs")),
        sa.UniqueConstraint(
            "telegram_chat_id", "telegram_message_id", name="uq_processing_jobs_telegram_message"
        ),
    )
    op.create_index(
        "idx_processing_jobs_claim",
        "processing_jobs",
        ["next_attempt_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("status IN ('pending', 'retry')"),
    )
    op.create_table(
        "bot_notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("operator_telegram_user_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_message_id", sa.BigInteger(), nullable=True),
        sa.Column("status", sa.String(length=30), server_default="pending", nullable=False),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["detected_questions.id"],
            name=op.f("fk_bot_notifications_question_id_detected_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_notifications")),
        sa.UniqueConstraint("question_id", name=op.f("uq_bot_notifications_question_id")),
    )
    op.create_table(
        "outbound_commands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("command_type", sa.String(length=20), nullable=False),
        sa.Column("reply_version", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("telegram_chat_id", sa.BigInteger(), nullable=False),
        sa.Column("source_message_id", sa.BigInteger(), nullable=False),
        sa.Column("topic_id", sa.BigInteger(), nullable=True),
        sa.Column("sent_message_id", sa.BigInteger(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "succeeded",
                "failed",
                "needs_review",
                name="outbound_command_status",
            ),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("attempt_count", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "next_attempt_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=100), nullable=True),
        sa.Column("last_error_code", sa.String(length=100), nullable=True),
        sa.Column("last_error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "command_type IN ('send_reply', 'edit_reply')",
            name=op.f("ck_outbound_commands_command_type_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["detected_questions.id"],
            name=op.f("fk_outbound_commands_question_id_detected_questions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbound_commands")),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_outbound_commands_idempotency_key")),
    )
    op.create_index(
        "idx_outbound_commands_claim",
        "outbound_commands",
        ["next_attempt_at", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_table(
        "question_chain_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("telegram_message_id", sa.BigInteger(), nullable=False),
        sa.Column("reply_to_message_id", sa.BigInteger(), nullable=True),
        sa.Column("author_telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("author_display_name", sa.String(length=255), nullable=True),
        sa.Column("telegram_created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=True),
        sa.Column("source_language", sa.String(length=10), nullable=True),
        sa.Column("translation_status", sa.String(length=30), nullable=False),
        sa.Column("is_target", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False),
        sa.CheckConstraint(
            "position BETWEEN 0 AND 9", name=op.f("ck_question_chain_messages_position_valid")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["detected_questions.id"],
            name=op.f("fk_question_chain_messages_question_id_detected_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_chain_messages")),
        sa.UniqueConstraint("question_id", "position", name="uq_chain_messages_question_position"),
        sa.UniqueConstraint(
            "question_id", "telegram_message_id", name="uq_chain_messages_question_message"
        ),
    )
    op.create_table(
        "reply_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.UUID(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('draft', 'sent', 'edited')", name=op.f("ck_reply_versions_action_valid")
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["detected_questions.id"],
            name=op.f("fk_reply_versions_question_id_detected_questions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reply_versions")),
        sa.UniqueConstraint(
            "question_id", "version_number", name="uq_reply_versions_question_version"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("reply_versions")
    op.drop_table("question_chain_messages")
    op.drop_index(
        "idx_outbound_commands_claim",
        table_name="outbound_commands",
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.drop_table("outbound_commands")
    op.drop_table("bot_notifications")
    op.drop_index(
        "idx_processing_jobs_claim",
        table_name="processing_jobs",
        postgresql_where=sa.text("status IN ('pending', 'retry')"),
    )
    op.drop_table("processing_jobs")
    op.drop_index("idx_detected_questions_operator_queue", table_name="detected_questions")
    op.drop_index("idx_detected_questions_expiry", table_name="detected_questions")
    op.drop_table("detected_questions")
    op.drop_table("translation_languages")
    op.drop_index(
        "idx_monitored_chats_active",
        table_name="monitored_chats",
        postgresql_where=sa.text("status = 'active'"),
    )
    op.drop_table("monitored_chats")
    op.drop_table("classification_runs")
    op.drop_table("application_settings")
    op.drop_table("api_usage_daily")
    for enum_name in (
        "outbound_command_status",
        "processing_job_status",
        "question_status",
        "monitored_chat_status",
        "monitored_chat_type",
    ):
        postgresql.ENUM(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
